// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://javfabcvxzgbobzoatef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphdmZhYmN2eHpnYm9iem9hdGVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5OTg3NzIsImV4cCI6MjA1NjU3NDc3Mn0.oNymtFAPbEnQYHzeQcZY12oh4DnFLf5ONZ_ecsXqiX0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);